# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics:

collections:
  albums:
    output: true
    permalink: /:title:output_ext

# UI configs
title: "Dana Salazar"
subtitle: "Things I see"
author: "Dana Salazar"
header:
 title: "Dana Salazar"
 subtitle: "Photography"
footer:
 name: "I'm Dana"
 bio: "An Edinburgh based photgrapher... etc..."
 github: ""
web_design:  "<a href = 'https://github.com/rampatra'>Ram Patra </a> X <a href = 'https://github.com/Evan-Moss'>Evan Moss </a>"
social_urls:
  facebook:
  twitter:
  instagram: "https://www.instagram.com/heyedinburgh/"
  dribbble:
  linkedin:
  github:
